"""Add cards table

Revision ID: 3971a142b659
Revises: caea1a67233f
Create Date: 2025-05-11 02:38:10.288647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3971a142b659'
down_revision = 'caea1a67233f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
